version: "3.7"

services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./:/app
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
        container_name: flawless-example-nginx
        restart: always
        depends_on:
            - php
        ports:
            - "7000:80"

    php:
        build:
            context: .
        volumes:
            - ./:/app/
        container_name: flawless-example-php
        depends_on:
            - postgres


    postgres:
        image: postgres:14.6-alpine
        container_name: flawless-example-postgres
        environment:
            POSTGRES_DB: ${PG_DB}
            POSTGRES_PASSWORD: ${PG_PASS}
            POSTGRES_USER: ${PG_USER}
        volumes:
            - postgres_data:/var/lib/postgresql/data:rw


volumes:
    postgres_data:
