version: "3.7"

services:
    nginx:
        image: nginx:alpine
        volumes:
            - ./:/app
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
        container_name: flawless-example-nginx
        restart: always
        depends_on:
            - php
        ports:
            - "7000:80"

    php:
        build:
            context: .
        volumes:
            - ./:/app/
        container_name: flawless-example-php
